### ISSUE TITLE
Are the correct event files shipped?

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy-fermi-lat-data#2]
I read through the scripts that prepare the data like [fermi_3fhl_data_prepare.sh](https://github.com/gammapy/gammapy-fermi-lat-data/blob/master/3fhl/fermi_3fhl_data_prepare.sh). In the script the following variables are defined

* ``EVENTS``
* ``EVENTS_SELECTED``
The latter being the output of ``gtselect``. The tools that run after ``gtselect``, however, take ``EVENTS`` as input parameter, e.g. [here](https://github.com/gammapy/gammapy-fermi-lat-data/blob/master/3fhl/fermi_3fhl_data_prepare.sh#L43). Also in [fermi_3fhl_data_config.yaml](https://github.com/gammapy/gammapy-fermi-lat-data/blob/master/3fhl/fermi_3fhl_data_config.yaml) the event list keyword seems to point to ``EVENTS``.

So is it correct to use ``EVENTS`` as input for the other tools and also use it in the analysis event though there is ``EVENTS_SELECTED``?

**Comment by adonath** [comment]
Note that there is an additional call to the `gtmktime` tool, that updates the good time intervals after `gtselect`. It uses the `EVENTS_SELECTED` as input and then writes the "final" event list to `EVENTS`.
This is then used later everywhere else. So the `fermi_3fhl_events_selected.fits` is only an intermediate result file, that is never really used (but I agree it's a misnomer...). Does that make sense or did you mean something else?

**Comment by joleroi** [comment]
> Note that there is an additional call to the gtmktime tool

Sorry, I missed that.
